realuser/urls.py
from django.urls import path

from . import views

app_name = "realuser"
urlpatterns= [
    path('', views.index , name= "index"),
    path('login', views.login_view , name= "login"),
    path('logout', views.logout_view , name= "logout"),
]

student/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('realuser/', include('realuser.urls')),
    
]
 

users/urls.py
from django.urls import path

from . import views

app_name = "users"
urlpatterns = [
    path('',views.index, name = "index"),
    path('<int:couses_id>' , views.do_couses , name = "couses"),
    path('<int:couses_id>/book' , views.book , name = "book"),
    path('<int:couses_id>/debook' , views.debook , name = "debook"),
    path('<int:couses_id>/admun' , views.admun , name = "admun"),
    
]

realuser/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.base import Model
# Create your models here.

class Couses(models.Model):
    subject = models.CharField(max_length=64)
    term = models.IntegerField()
    couseid = models.IntegerField()
    num_student = models.IntegerField()
    year = models.IntegerField()
    nisit = models.ManyToManyField(User, blank=True,name="nisit")
    status = models.BooleanField(default=True)

    def is_full(self):
        if self.nisit.count() == self.num_student:
            return True
        return False

    def __str__(self):
        return f"{self.id}:Subject {self.subject} | Couses ID {self.couseid} "

realuser/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
import sys
sys.path.append('../')
from users.models import *
# Create your views here.

def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("realuser:login"))
    else:
        couseslist = []
        for c in Couses.objects.all():
            if request.user in c.nisit.all():
                couseslist.append(c)
        return render(request, "realuser/index.html",{
            "couseslist" : couseslist
        })

def login_view(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse("realuser:index"))

    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("realuser:index"))
        else:
            return render(request, "realuser/login.html", {"fail": "Invalid credential"})
    return render(request, "realuser/login.html")

def logout_view(request):
    logout(request)
    messages.success(request, "Logged out.")
    return render(request, "realuser/login.html", {
        "messages": messages.get_messages(request)
    })

users/views.py
from django.http.response import HttpResponse, HttpResponseRedirect
import users 
from django.shortcuts import get_object_or_404, render 
from .models import Couses
from django.urls import reverse

# Create your views here.
def index(request):
    
    return render(request, "users/index.html",
    {
        "couses" : Couses.objects.all(),
        
    })
def do_couses(request , couses_id):
    
    couses = get_object_or_404(Couses, pk = couses_id)
        
    
    return render(request, "users/couses.html",{
        "couses" : couses,
        "portai" : couses.nisit.all(),
        "check"  : couses.is_full() ,
        "keekon" : couses.nisit.count(),
        

        
        
        
    })
def book(request, couses_id):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("realuser:login"))

    couses = get_object_or_404(Couses, pk = couses_id)
    if request.user not in couses.nisit.all():
        couses.nisit.add(request.user)
        couses.save()
    return HttpResponseRedirect(reverse("users:couses",args=(couses_id,)))

def debook(request, couses_id):
    couses = get_object_or_404(Couses, pk = couses_id)
    if request.user  in couses.nisit.all():
        couses.nisit.remove(request.user)
        couses.save()
    return HttpResponseRedirect(reverse("users:couses",args=(couses_id,)))

def admun(request, couses_id):
    if request.user.is_superuser:
        count = Couses.objects.get(id = couses_id)
        if count.status:
            count.status = False
            count.save()
        else:
            count.status = True
            count.save()
    return HttpResponseRedirect(reverse("users:couses", args=(couses_id,)))

realuser/templates/realuser/index.html
{% extends "realuser/layout.html" %}

{% block body %}
    <style>
        body {
        background-image: url("https://source.unsplash.com/GcDgpyhmR_c");
        background-size: cover;
        font-family: 'Rokkitt', serif;
        font-size: 24px;
      }
    </style>
    <div style="padding-left: 2%; padding-top:2%">
    <h1 style="color:white">Welcome, {{ request.user.first_name }}</h1>

    <ul>
        <li style="color:white">Username: {{ request.user.username }}</li>
        <li style="color:white">Email: {{ request.user.email }}</li>
    </ul>
    <h1 style="color:white"> Registered </h1>
    {% for x in couseslist %}
        <div style="color:white">
        {{ x.subject }} <br>
        {% empty %}
        <li style="color:white">No Courses</li>
        </div>
    {% endfor %}

    <br>
    <div style=" margin-bottom: 1%;margin-left: 2%"><a href="{% url 'users:index' %}"class="btn btn-outline-light">All Courses</a></div>
    
    
    <div style=" margin-bottom: 1%;margin-left: 2%"><a href="{% url 'realuser:logout' %}"class="btn btn-outline-danger">Logout</a></div>
    </div>
{% endblock %}

realuser/templates/realuser/layout.html
<!DOCTYPE html>
{% load static %}
<html>
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Rokkitt">
    <style>
        body {
        font-family: 'Rokkitt', serif;
        
        font-size: 24px;
      }
    </style>
    <head>
        <link rel="stylesheet" href="{% static 'styles/styles.css' %}"/>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
        <title>Users</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    </head>
    <body>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-W8fXfP3gkOKtndU4JGtKDvXbO53Wy8SZCQHczT5FMiiqmQfUpWbYdTil/SxwZgAN" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.min.js" integrity="sha384-skAcpIdS7UcVUC05LJ9Dxay8AXcDYfBJqt1CJ85S/CFujBsIzCIv+l9liuYLaMQ/" crossorigin="anonymous"></script>
        {% block body %}
        {% endblock %}
    </body>
</html>

realuser/templates/realuser/login.html
{% extends "users/layout.html" %}

{% block body %}

    {% if messages %}
        {% for message in messages %}
        <div{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
        {% endfor %}
    {% endif %}

    <form action="{% url 'realuser:login' %}" method="post">
        {% csrf_token %}
        <input type="text" name="username" placeholder="Username">
        <input type="password" name="password" placeholder="Password">
        <input type="submit" value="Login">
    </form>

{% endblock %}

realuser/templates/realuser/login2.html
{% extends "realuser/layout.html" %}
{% load static %}
{% block body %}

    {% if messages %}
        {% for message in messages %}
        <div{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
        {% endfor %}
    {% endif %}

    <form action="{% url 'realuser:login' %}" method="post">
        {% csrf_token %}
        <input type="text" name="username" placeholder="Username">
        <input type="password" name="password" placeholder="Password">
        <input type="submit" value="Login">
    </form>

{% endblock %}

<div class="login-wrap">
	<div class="login-html">
		<input id="tab-1" type="radio" name="tab" class="sign-in" checked><label for="tab-1" class="tab">Sign In</label>
		<div class="login-form">
			<div class="sign-in-htm">
				<div class="group">
					<label for="user" class="label">Username</label>
					<input id="user" type="text" class="input">
				</div>
				<div class="group">
					<label for="pass" class="label">Password</label>
					<input id="pass" type="password" class="input" data-type="password">
				</div>
				<div class="group">
					<input type="submit" class="button" value="Sign In">
				</div>
				<div class="hr"></div>
			</div>
			
		</div>
	</div>
</div>

users/templates/users/couses.html
{% extends "users/layout.html" %}

{% block body %}
    <div style="color:white;margin-left:1%"><h1>
        Course  {{ couses.id }} Detail
    </h1></div>
    <u1>
        <div style="color:white;margin-left:1%">
        <li>Course Name     : {{ couses.subject}}</li>
        <li>Sememster  : {{couses.term}}</li>
        <li>Year       : {{couses.year}}</li>
        <li>Student    : {{ keekon }} / {{couses.num_student}}</li>
        <li>Status     : {% if couses.status %}
                    <b style="color: green;">Avaliable</b>
                    {%else%}
                    <b style="color: rgb(255, 9, 9);">Unvaliable</b>
                
                    {% endif %}
        </li></div>
        
        
   
    </u1>
    {% if request.user.is_superuser %}
    <br>
    <div style="color:white;margin-left:1%"><h3> Student </h3></div>
    <ul>
        {% for student in portai %}
        <li style="color:white">
            {{ student.first_name }} {{ student.last_name }}
        </li>
        {% empty %}
        <li style="color:white">
            No student
        </li>
        {% endfor %}
    </ul>
    
    {% else %}
   
    {% endif %}
    
    {% if request.user not in portai %}
        {% if couses.status %}
        <div style="margin-left:1%;margin-top:1%"><p><a href="{% url 'users:book' couses.id %}"class="btn btn-outline-success">Register</a></h3></div>
        {% else %}
        
        {% endif %}
    {% else %}
    <br>
    <div style="color:rgb(51, 255, 0);margin-left:1%"><h0>
        Already Register </h0></div>
    <br>
    <br>
    <div style="margin-left:1%">
    <p ><a href="{% url 'users:debook' couses.id %}"class="btn btn-outline-danger">Withdraw</a></div>
    
    {% endif %}
    

    <div style="margin-left:1%;margin-top:1%"><a href = "{% url 'users:index' %}"class="btn btn-outline-light">Back to menu</a></div>
    {% if request.user.is_superuser %}
    <br>
    <div style="margin-left:1%"><a href="{% url 'users:admun' couses.id %}"class="btn btn-outline-light">Switch Status</a></div>
    {% else %}
   
    {% endif %}
{% endblock %}

users/templates/users/index.html
{% extends "users/layout.html" %}
{% load static %}
{% block body %}
    
    <h1 style="color:white;margin-top:1%; margin-left:1%">
    Course List
    </h1>
    <br>
    <ul>
    {% for couses in couses %}
        <li>
            <a href = "{% url 'users:couses' couses.id %}">{{ couses }}</a>
        </li>
    {% endfor %}
    </ul>
    <br>
    <br>
    <div style="margin-left:1%"><a href="{% url 'realuser:index' %}" class="btn btn-outline-light">Back to homepage</a>
    </div>
{% endblock %}

users/templates/users/layout.html
<!DOCTYPE html>
<html>
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Rokkitt">
    <style>
        body {
        background-image: url("https://source.unsplash.com/5sljLx01YwI");
        background-size: cover;
        font-family: 'Rokkitt', serif;
        font-size: 24px;
      }
    </style>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
        <title>
            Couses
        </title>
    </head>
    <body>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-W8fXfP3gkOKtndU4JGtKDvXbO53Wy8SZCQHczT5FMiiqmQfUpWbYdTil/SxwZgAN" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.min.js" integrity="sha384-skAcpIdS7UcVUC05LJ9Dxay8AXcDYfBJqt1CJ85S/CFujBsIzCIv+l9liuYLaMQ/" crossorigin="anonymous"></script>
        {% block body %}
        {% endblock %}
    </body>
</html>